# Jekyll configuration**

name: Octocat's Wanderings
description: Chronicles of my adventures in coding  
url: "https://octoca.github.io"
markdown: kramdown
highlighter: rouge

theme: jekyll-theme-minimal
